#!/bin/sh

#
# init.sh
#
# This script dynamically generates the valkey.conf file using environment variables
# and then starts the Valkey server with that configuration.

# --- Configuration ---
: ${VALKEY_PORT:=6379}
: ${VALKEY_PASSWORD:="v3rhsYtVfHG7AVKSKZK"}

CONFIG_DIR="/usr/local/etc/valkey"
CONFIG_FILE="$CONFIG_DIR/valkey.conf"

mkdir -p "$CONFIG_DIR"

echo "INFO: Generating Valkey configuration at $CONFIG_FILE"
echo "INFO: Using PORT: $VALKEY_PORT"

# Use a Here-Document to write the entire configuration file.
# Variables inside the EOF block are dynamically substituted.
cat <<EOF >"$CONFIG_FILE"
# Generated by init.sh script from Docker environment variables

# General settings
port ${VALKEY_PORT}
# daemonize no
# pidfile /var/run/valkey_${VALKEY_PORT}.pid
# loglevel notice
# logfile ""
# databases 16

# Persistence settings
# save 900 1
# save 300 10
# save 60 10000
# dbfilename dump.rdb
# dir ./

# Replication settings (for a replica)
# replicaof 127.0.0.1 ${VALKEY_PORT}
# masterauth your_master_password

# Security settings
requirepass ${VALKEY_PASSWORD}
# maxclients 10000
# maxmemory 2gb
# maxmemory-policy allkeys-lru

# Client limits
# timeout 0
# tcp-keepalive 300

# Append Only File (AOF) persistence
# appendonly no
# appendfilename "appendonly.aof"
# appendfsync everysec
# no-appendfsync-on-rewrite yes
# auto-aof-rewrite-percentage 100
# auto-aof-rewrite-min-size 64mb

# Cluster settings (if used)
# cluster-enabled yes
# cluster-config-file nodes-${VALKEY_PORT}.conf
# cluster-node-timeout 15000
EOF

echo "INFO: Configuration file written successfully. Starting Valkey server..."
# Redis warning message: https://github.com/jemalloc/jemalloc/issues/1328
# This command doesn't work. Seems to be WSL problem, will ignore for now.
# sysctl vm.overcommit_memory=1

# Execute the Valkey server with the generated configuration file.
# Using 'exec' replaces the current shell process with the Valkey process,
# which is crucial for proper signal handling in Docker.
exec valkey-server "$CONFIG_FILE"
