"""
Django settings for main project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from main.settings_matr import MaterialsControllerConfig
from main.settings_sales import SalesControllerConfig
from main.settings_ops import OpsControllerConfig
from main.utils import get_boolean_env_var, parse_mongo_uri

load_dotenv()


# TODO: automate retrieval of version control with git
GIT_VERSION = "v0.0.0"

# Displays a red banner to warn user of dev environment
IS_DEVELOPMENT = get_boolean_env_var("IS_DEVELOPMENT_ENV", default=False)

APP_NAME = "jetforge"
_APP_DATA = os.getenv("APP_DATA", "~")
match _APP_DATA:
    case x if "~" in x:
        APP_DATA = Path(x).expanduser() / APP_NAME
    case "":
        APP_DATA = Path("~").expanduser() / APP_NAME
    case _:
        APP_DATA = Path(_APP_DATA) / APP_NAME

FORCE_SCRIPT_NAME = os.getenv("PROXY_PREFIX", "")
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-nd_*!k0%5fw-n79s7)b95+(4^f$25*41v#vc3d&@z01(7*n(0*",
)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_boolean_env_var("DJANGO_DEBUG", default=False)
DJANGO_SUPERUSER_ADMIN = os.getenv("DJANGO_SUPERUSER_ADMIN", "admin")
DJANGO_SUPERUSER_EMAIL = os.getenv("DJANGO_SUPERUSER_EMAIL", "admin@pdixbmqzjl.com")
# DJANGO_SUPERUSER_PASSWORD is handled by init_superuser.py

#######################################
# Directory and Logging configuration
#######################################
BASE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_LOG_DIRPATH = APP_DATA / "logs"
_LOG_DIRPATH = os.getenv("DJANGO_LOGS_ROOT", "")
match _LOG_DIRPATH:
    case x if "~" in x:
        LOG_DIRPATH = Path(x).expanduser() / APP_NAME
        LOG_DIRPATH.mkdir(parents=True, exist_ok=True)
    case "":
        LOG_DIRPATH = DEFAULT_LOG_DIRPATH
    case _:
        LOG_DIRPATH = Path(_LOG_DIRPATH)
if not LOG_DIRPATH.is_dir():
    LOG_DIRPATH.mkdir(parents=True, exist_ok=True)
LOGFILE_FILEPATH = LOG_DIRPATH / "app-logs.log"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{LOGFILE_FILEPATH.absolute()}",
            "formatter": "verbose",
            "when": "D",
            "interval": 1,
            "backupCount": 365,
            "utc": True,
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}


#######################################
# Django Settings
#######################################


INSTALLED_APPS = [
    "main.apps.MongoAdminConfig",
    "main.apps.MongoAuthConfig",
    "main.apps.MongoContentTypesConfig",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.forms",
    "crispy_forms",
    "crispy_bootstrap5",
    "django_bootstrap5",
    "django_filters",
    "django_tables2",
    "django_select2",
    "django_htmx",
    "django_json_widget",
    "creds",  # urls will be added in url.py manually
    "recon",  # urls will be added in url.py manually
]
APP_MODULES = [
    # urls will be added automatically in main.urls.py
    "app",
    "joborders",
    "engines",
    "customers",
    "materials",
    "sales",
    "operations",
]
INSTALLED_APPS.extend(APP_MODULES)
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"
ROOT_URLCONF = "main.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.get_git_version",
                "main.context_processors.is_development_environment",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.bkxuy7afeyjkufrr.com")
EMAIL_PORT = os.getenv("EMAIL_PORT", 25)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "webmaster@bkxuy7afeyjkufrr.com")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
EMAIL_FAIL_SILENTLY = get_boolean_env_var("EMAIL_FAIL_SILENTLY", default=False)
EMAIL_USE_LOCALTIME = True
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", 1))


#######################################
# Third party extensions settings
#######################################
# Extensions required
DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap5.html"
DJANGO_TABLES2_TABLE_ATTRS = {
    "class": "table table-hover",
    "thead": {
        "class": "table-light",
    },
    "style": "white-space: nowrap; overflow-x: auto;",
}
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

#######################################
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# #######################################
MGDB_CONNECTION_STR = os.getenv(
    "MGDB_CONNECTION_STR", "mongodb://localhost:27017/default_db"
)
mgdb_params = parse_mongo_uri(MGDB_CONNECTION_STR)
DATABASES = {
    "default": {
        "ENGINE": "django_mongodb_backend",
        "HOST": MGDB_CONNECTION_STR,
        "NAME": mgdb_params.db,
    },
}

# Database routers
# https://docs.djangoproject.com/en/dev/ref/settings/#database-routers
DATABASE_ROUTERS = ["django_mongodb_backend.routers.MongoRouter"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django_mongodb_backend.fields.ObjectIdAutoField"
MIGRATION_MODULES = {
    "admin": "mongo_migrations.admin",
    "auth": "mongo_migrations.auth",
    "contenttypes": "mongo_migrations.contenttypes",
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


############################################
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
############################################

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Singapore"
USE_I18N = True
USE_TZ = True
# These uses Django's date format syntax (PHP)
SHORT_DATE_FORMAT = "Y-m-d"
SHORT_DATETIME_FORMAT = "Y-m-d HM"
DATETIME_FORMAT = "Y-m-d H:M:s"
TIME_FORMAT = "H:M:s"
DATE_INPUT_FORMATS = [
    "%Y-%m-%d",  # '2006-10-25'
    "%m/%d/%Y",  # '10/25/2006'
    "%m/%d/%y",  # '10/25/06'
    "%b %d %Y",  # 'Oct 25 2006'
    "%b %d, %Y",  # 'Oct 25, 2006'
    "%d %b %Y",  # '25 Oct 2006'
    "%d %b, %Y",  # '25 Oct, 2006'
    "%B %d %Y",  # 'October 25 2006'
    "%B %d, %Y",  # 'October 25, 2006'
    "%d %B %Y",  # '25 October 2006'
    "%d %B, %Y",  # '25 October, 2006'
    "%d%m%y",  # 251026
]
TIME_INPUT_FORMATS = [
    "%H:%M:%S",  # '14:30:59'
    "%H:%M:%S.%f",  # '14:30:59.000200'
    "%H:%M",  # '14:30'
    "%H%M",  # 1430
]
DATETIME_INPUT_FORMATS = [
    "%Y-%m-%d %H:%M:%S",  # '2006-10-25 14:30:59'
    "%Y-%m-%d %H:%M:%S.%f",  # '2006-10-25 14:30:59.000200'
    "%Y-%m-%d %H:%M",  # '2006-10-25 14:30'
    "%m/%d/%Y %H:%M:%S",  # '10/25/2006 14:30:59'
    "%m/%d/%Y %H:%M:%S.%f",  # '10/25/2006 14:30:59.000200'
    "%m/%d/%Y %H:%M",  # '10/25/2006 14:30'
    "%m/%d/%y %H:%M:%S",  # '10/25/06 14:30:59'
    "%m/%d/%y %H:%M:%S.%f",  # '10/25/06 14:30:59.000200'
    "%m/%d/%y %H:%M",  # '10/25/06 14:30'
    "%d%m%y %H%M",  # 251026 1430
    "%d%m%y_%H%M",  # 251026_1430
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_URL = os.getenv("DJANGO_STATIC_URL", "static/")
_STATIC_ROOT = os.getenv("DJANGO_STATIC_ROOT", "")
if _STATIC_ROOT:
    match _STATIC_ROOT:
        case x if "~" in x:
            STATIC_ROOT = Path(_STATIC_ROOT).expanduser()
        case _:
            STATIC_ROOT = Path(_STATIC_ROOT)
else:
    STATIC_ROOT = BASE_DIR / "staticfiles"
if not STATIC_ROOT.is_dir():
    try:
        STATIC_ROOT.mkdir(parents=True)
    except Exception as e:
        print(f"Failed to set STATIC_ROOT; {e=}")


MEDIA_URL = os.getenv("DJANGO_MEDIA_URL", "media/")
_MEDIA_ROOT = os.getenv("DJANGO_MEDIA_ROOT", "")
if _MEDIA_ROOT:
    match _MEDIA_ROOT:
        case x if "~" in x:
            MEDIA_ROOT = Path(_MEDIA_ROOT).expanduser()
        case _:
            MEDIA_ROOT = Path(_MEDIA_ROOT)
else:
    MEDIA_ROOT = BASE_DIR / "mediafiles"
if not MEDIA_ROOT.is_dir():
    try:
        MEDIA_ROOT.mkdir(parents=True)
    except Exception as e:
        print(f"Failed to set MEDIA_ROOT; {e=}")


CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Singapore"  # Use your desired timezone
CELERY_TASK_ALWAYS_EAGER = (
    os.getenv("CELERY_TASK_ALWAYS_EAGER", "False").lower() == "true"
)  # For local synchronous testing
CELERY_TASK_SOFT_TIME_LIMIT = os.getenv(
    "CELERY_TASK_SOFT_TIME_LIMIT", 60
)  # Tasks must finish in 60 seconds (soft)
CELERY_TASK_TIME_LIMIT = os.getenv(
    "CELERY_TASK_TIME_LIMIT", 90
)  # Tasks must be killed after 90 seconds (hard)

#######################################
# Application Defined Settings
#######################################

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "n1-a697e7d4-01",
    "n1-a697e7d4-01.stengggrp.local",
    "n1-1022-011232",
    "n1-1022-011232.stengggrp.local",
    "10.32.80.204",  # n1-a697e7d4-01 wifi
    "10.32.81.88",  # n1-a697e7d4-01 ethernet
    "10.32.81.193",  # n1-1022-011232 wifi
]
ENV_ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS")
if ENV_ALLOWED_HOSTS:
    ENV_ALLOWED_HOSTS = ENV_ALLOWED_HOSTS.split(",")
    ALLOWED_HOSTS.extend(ENV_ALLOWED_HOSTS)
AUTH_USER_MODEL = "creds.UserModel"
LOGIN_URL = "creds:login"
LOGIN_REDIRECT_URL = "creds:user_me"
LOGOUT_REDIRECT_URL = "landing"
AUTHENTICATION_BACKENDS = ["creds.backends.UserEmailAuthBackend"]
ALLOWED_EMAIL_DOMAINS = [os.getenv("ALLOWED_EMAIL_DOMAIN", "stengg.com")]
CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS]

# Tell Django to use the project's TEMPLATES settings for rendering forms
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"


#######################################
# Load config from other applications
#######################################

MATR_CONF = MaterialsControllerConfig(media_root=MEDIA_ROOT)
SALES_CONF = SalesControllerConfig(media_root=MEDIA_ROOT)
OPS_CONF = OpsControllerConfig(media_root=MEDIA_ROOT)
